language: crystal
services:
  - postgresql
before_script:
  - psql -c 'create database todo_tasks;' -U postgres
env:
  - PG_DATABASE_URL=postgresql://postgres@localhost/todo_tasks
install:
  - shards install
script:
  - crystal spec
  - bin/ameba
